export const VENEZUELAN_CITIES = [
    "Caracas",
    "Maracaibo",
    "Valencia",
    "Barquisimeto",
    "Maracay",
    "Ciudad Guayana",
    "Barcelona",
    "Maturín",
    "Ciudad Bolívar",
    "Cumaná",
    "San Cristóbal",
    "Barinas",
    "Puerto La Cruz",
    "Coro",
    "Puerto Ordaz",
    "Mérida",
    "San Juan de los Morros",
    "Acarigua",
    "Tucupita",
    "Guanare",
    "San Felipe",
    "La Asunción",
    "San Fernando de Apure",
    "Trujillo",
    "San Carlos",
    "Los Teques",
    "Punto Fijo",
    "Puerto Cabello",
    "El Tigre",
    "Cabimas",
    "Guarenas",
    "Ocumare del Tuy"
];