# Generated by Django 5.2.6 on 2025-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
