# Generated by Django 5.2.6 on 2025-10-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.CharField(choices=[('disponile', 'Disponible'), ('oferta', 'Oferta'), ('agotado', 'Agotado')], default='disponible', max_length=50),
        ),
    ]
